version: 2
builds:
  - id: "sketchy"
    binary: "sketchy"
    env:
        - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/main.go